version: '2.1'

services:
  

  postgres:
    build: postgres
    restart: always
    environment:
      POSTGRES_USER: userP
      POSTGRES_PASSWORD: mypass
      POSTGRES_DB: facedb
    volumes:
      - postgres_data:/var/lib/pg/data
      - ./postgres/init.sh:/docker-entrypoint-initdb.d/init.sh
      - ./postgres/testDB.sql:/docker-entrypoint-initdb.d/testDB.sql
    ports:
      - 5432:5432
        
  redis:
    image: "redis:6"
    



volumes:
  postgres_data: